apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: istio-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: istio
  path: ./istio
  prune: true